### PR TITLE
feature: temporary url support

### PR DESCRIPTION
**Pull request by WalrusSoup**
# Temporary URL Support
This PR adds support for temporary urls based on [this documentation](https://support.bunny.net/hc/en-us/articles/360016055099-How-to-sign-URLs-for-BunnyCDN-Token-Authentication) and validated using the first-party example [here](https://github.com/BunnyWay/BunnyCDN.TokenAuthentication) and solves this issue https://github.com/PlatformCommunity/flysystem-bunnycdn/issues/50

**Important Notes**
* `/assets/` inside of the pullzone in tests were rewritten to include `/assets/` in the call instead. I am not sure why this was done, because as far as I can see with bunny we are required to set the pullzone to point into a storage point in its entirety. 
* I wanted to add the pullzone auth token as a parameter on the adapter because it is different than the storage API key, but adding another key broke the arg-check (its limited to 2 args) - so I added it as a separate call `setPullzoneToken` 

**Tests Added**
* `test_generating_a_temporary_url`
* `test_generating_temporary_url_supports_image_optimization` 

## Example Usage
Setup adapter:
```php
$time = (new \DateTime('now'))->modify('+5 minutes');
$adapter = new \PlatformCommunity\Flysystem\BunnyCDN\BunnyCDNAdapter($client, new BunnyPullZone('https://[redacted].b-cdn.net', '');
$adapter->temporaryUrl('/images/saber2.png', $time);

//  https://[redacted]/images/saber2.png?token=[redacted]&expires=1674085360
```
saber2

With support for optimizer params:
```php
$adapter->temporaryUrl('/images/saber2.png', $time, ['width' => 200]);

// https://[redacted]/images/saber2.png?token=[redacted]&width=200&expires=1674085307

```
saber2-smol

### CODE REVIEW

**Comment by tinect** [comment]
Great work! Thank you.

I'm confused by the taken name `pullZoneKey`. Could you please name it more meaningful? It doesn't sound like it belongs to the `Token Authentification` to me.

On bunnyCDN panel it's called `Url Token Authentication Key`, but in API it's called `ZoneSecurityKey`, damn :-(

**Comment by WalrusSoup** [comment]
> On bunnyCDN panel it's called `Url Token Authentication Key`, but in API it's called `ZoneSecurityKey`, damn :-(

Totally agree with the confusing names. The fact that token authentication is per pull zone is why I chose the name pullzonekey. I didn't want to use token, because token makes it sound like its the primary user token or uploads when it's not.

I think that it may be best to go with my previous suggestion that the zone configuration(s) be pulled into a new class and that class can then be responsible for public url generation, signed urls. 

```php
$zone = new BunnyPullZone($config['default_zone'], $config['default_zone_security_token']);
$zone->publicUrl('whatever.png');
$zone->temporaryUrl('whatever.png');
```

I think this would make sense and solve the issue in a more natural way. 🤔  hmmm, maybe I can commit an example and see how it feels? 

Only concern would be that it would be a breaking change on the api (which may need to happen at some point anyway as the current one limits to 2 args in the constructor or it throws).

**Comment by WalrusSoup** [comment]
Ima close this for now - i think a larger overhaul is in order and i believe bunny should be finish s3 compatible drivers soon.

**Comment by sifex** [comment]
Hey @WalrusSoup , lmk if you want to reopen this I can have a look at merging tonight

**Pull request closed without merging**
